# Generated by Django 4.1.2 on 2022-10-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notic',
            name='desc',
            field=models.TextField(),
        ),
    ]
