# Generated by Django 4.1.2 on 2022-11-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('pasw', models.TextField()),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('SecKey', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('stu_12', 'Student - 12'), ('stu_11', 'Student - 11'), ('stu_8_10', 'Student - 8 to 10')], max_length=20)),
            ],
        ),
    ]
