# Generated by Django 4.1.2 on 2022-10-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('pasw', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
