# Generated by Django 4.1.2 on 2022-10-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('stu_12', 'Student - 12'), ('stu_11', 'Student - 11'), ('stu_8_10', 'Student - 8 to 10')], max_length=20)),
            ],
        ),
    ]
