# Generated by Django 4.1.2 on 2022-11-23 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomStudent',
        ),
    ]
