# Generated by Django 4.1.2 on 2022-11-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_customstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pasw',
            field=models.TextField(),
        ),
    ]
