# Generated by Django 4.1.2 on 2022-10-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userrole_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='username',
            field=models.CharField(choices=[('stu_12', 'Student - 12'), ('stu_11', 'Student - 11'), ('stu_8_10', 'Student - 8 to 10')], max_length=50),
        ),
    ]
