# Generated by Django 4.1.2 on 2022-10-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userrole_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='username',
            field=models.CharField(choices=[], max_length=50),
        ),
    ]
