# Generated by Django 4.1.2 on 2022-10-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userrole_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
