# Generated by Django 4.1.2 on 2022-10-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userrole_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pasw',
            field=models.CharField(max_length=150),
        ),
    ]
