# Generated by Django 4.1.2 on 2022-10-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_pasw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
